### ISSUE TITLE
Question: How to debug when NV brings up no results?

### ISSUE THREAD

**Issue by al3xandru** [alok/notational-fzf-vim#56]
## Checklist

- [X] I updated.

- [X] `NV_note_handler` cannot fix my issue.

## Summary of Problem

1.  I updated the plugin and set `let g:nv_search_paths = ['~/real_path_here']`.  
2.  I do have `rg` installed

    ```
    > which rg
   /usr/local/bin/rg

3.  I have the fzf vim plugin installed

    ```
    Plugin 'junegunn/fzf'
    Plugin 'junegunn/fzf.vim'
    let g:fzf_layout = {'up': '~20%'}
    ```

When invoking `:NV` the results window is open but there is nothing in there.  There are 792 files in directory though. How can I understand what's going on?

**Comment by alok** [comment]
Put up a gist of 1 of those files, along with its actual filename.

**Comment by al3xandru** [comment]
As requested: https://gist.github.com/al3xandru/7eda0bcdb0b07147b397260529e1fd19

In general:

* the majority of the files start with `qq-`
* have the extension `.md` or `.markdown`
* might contain spaces in their name

Is there anything in particular you suspect?

**Comment by al3xandru** [comment]
I'm starting to suspect that this is related to the python dependency.  Once I've set `let g:nv_use_short_pathnames=0` disabling the path processing (done with Python) the list of files got populated.  The preview is not which could confirm my hypothesis.  What do you think?

**Comment by al3xandru** [comment]
Confirmed.  The behavior is related to python dependency.  I use pyenv and even if I do have a version of Python 3 available, simply calling `python3` won't work.

I do recognize this is probably a very rare case, but it would be very cool if the plugin would allow to specify the `pypy3` or `python3` paths.

**Comment by alok** [comment]
Will take PR, but won't work on this. You may be able to hook into Neovim's functionality for "host programs", dunno about vim.

**Comment by vcavallo** [comment]
Also running in to this, and very grateful to @al3xandru for pointing out the issue! I recently changed my Python environment and whole directories dropped out of my nv search results. using `let g:nv_use_short_pathnames=0` is a workaround, but a bit of a bummer.

I understand that this issue is closed - just wanted to note my confirmation. If I find a better solution I'll update here or open a PR.

**Comment by vcavallo** [comment]
I was trying to write up a quick PR to allow the user to provide a python executable path, but now I'm even more confused because the python executable that notational-fzf-vim has _is_ my python3 executable... Which happens to be version `3.8.5`.

Perhaps this is actually a Python version issue within Python3? 

@alok, which version of Python3 do you expect this to work with?
